#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_town = env_modules.Clone()

env_town.Prepend(
    CPPPATH=[
        "#modules/town_sdk/include",
        "#modules/town_sdk",
        "#thirdparty/enet",
    ]
)

module_obj = []

env_town.add_source_files(module_obj, "*.cpp")
env_town.add_source_files(module_obj, "src/*.cpp")

env.modules_sources += module_obj
