#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")  # noqa: F821
Import("env_modules")  # noqa: F821

env_goap = env_modules.Clone()  # noqa: F821

env_goap.add_source_files(env.modules_sources, "*.cpp")  # noqa: F821
env_goap.add_source_files(env.modules_sources, "editor/*.cpp")  # noqa: F821
