#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_sixway_mtl = env_modules.Clone()

# Add Source Files
env_sixway_mtl.add_source_files(env.modules_sources, "*.cpp")
