short_name = "blazium"
name = "Blazium Engine"
major = 4
minor = 6
patch = 2
status = "stable"
module_config = ""
website = "https://blazium.app"
docs = "4.6"
external_major = 0
external_minor = 8
external_patch = 0
external_status = "dev"
external_sha = "001aa128b1cd80dc4e47e823c360bccf45ed6bad"
mirror_list = "https://blazium.app/api/mirrorlist/"
version_url = "https://blazium.app/api/versions-" + external_status + ".json"
