short_name = "blazium"
name = "Blazium Engine"
major = 4
minor = 3
patch = 2
status = "stable"
module_config = ""
website = "https://blazium.app"
docs = "4.3"
external_major = 0
external_minor = 6
external_patch = 0
external_status = "dev"
external_sha = "b6848ff2752d2959c58c8bbf15320dbe0899e58e"
mirror_list = "https://blazium.app/api/mirrorlist/"
version_url = "https://blazium.app/api/versions-" + external_status + ".json"
