short_name = "blazium"
name = "Blazium Engine"
major = 4
minor = 4
patch = 1
status = "stable"
module_config = ""
website = "https://blazium.app"
docs = "4.4"
external_major = 0
external_minor = 7
external_patch = 0
external_status = "dev"
external_sha = "45fc515ae3574e9c1f9deacaa6960dec68a7d38b"
mirror_list = "https://blazium.app/api/mirrorlist/"
version_url = "https://blazium.app/api/versions-" + external_status + ".json"
