#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_rcon = env_modules.Clone()

# Add all .cpp files in the module root
env_rcon.add_source_files(env.modules_sources, "*.cpp")
