#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import default_theme_builders

sources = [
    "theme_db.cpp",
    "theme_owner.cpp"
]

if env["legacy_theme"]:
    sources += ["default_theme.cpp"]
else:
    sources += ["blazium_default_theme.cpp"]

env.add_source_files(env.scene_sources, sources)

SConscript("icons/SCsub")

env.CommandNoCache(
    "#scene/theme/default_font.gen.h",
    "#thirdparty/fonts/OpenSans_SemiBold.woff2",
    env.Run(default_theme_builders.make_fonts_header),
)
