#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_godotsteam = env_modules.Clone()

# Thirdparty source files
thirdparty_obj = []
thirdparty_dir = "#thirdparty/steam/"
env_godotsteam.Prepend(CPPPATH=[thirdparty_dir])

env_thirdparty = env_godotsteam.Clone()
env_thirdparty.disable_warnings()
env.modules_sources += thirdparty_obj

# Godot source files
module_obj = []
env_godotsteam.Append(CPPDEFINES=["STEAM_API_NODLL"])
env_godotsteam.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
