#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_dotini = env_modules.Clone()

# Blazium source files
env_dotini.add_source_files(env.modules_sources, "*.cpp")
